# Build Stage
FROM node:18 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Production Stage
FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
